/*
 * ESI Meta Spec
 *
 * ESI specs and miscellaneous routes
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SSO /verify JSON
type GetVerifyOk struct {
	// Token owner's character ID
	CharacterID int32 `json:"CharacterID"`
	// Token owner's character name
	CharacterName string `json:"CharacterName,omitempty"`
	// Hash of the character's owner. If the character is sold or otherwise transferred, this will change
	CharacterOwnerHash string `json:"CharacterOwnerHash,omitempty"`
	// Expiry time of the token (not RFC3339)
	ExpiresOn string `json:"ExpiresOn,omitempty"`
	// The IP which generated the token
	IntellectualProperty string `json:"IntellectualProperty,omitempty"`
	// Space separated list of scopes the token is valid for
	Scopes string `json:"Scopes,omitempty"`
	// Type of access token
	TokenType string `json:"TokenType,omitempty"`
}
