/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// response object
type PutCharactersCharacterIdCalendarEventIdResponse struct {
	// response string
	Response string `json:"response"`
}
