/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 422 unprocessable entity object
type PostFleetsFleetIdMembersUnprocessableEntity struct {
	// error message
	Error_ string `json:"error,omitempty"`
}
