/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// head object
type GetCharactersCharacterIdPlanetsPlanetIdHead struct {
	// head_id integer
	HeadId int32 `json:"head_id"`
	// latitude number
	Latitude float32 `json:"latitude"`
	// longitude number
	Longitude float32 `json:"longitude"`
}
