/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 201 created object
type PostCharactersCharacterIdFittingsCreated struct {
	// fitting_id integer
	FittingId int32 `json:"fitting_id"`
}
