/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// jump_clone object
type GetCharactersCharacterIdClonesJumpClone struct {
	// implants array
	Implants []int32 `json:"implants"`
	// jump_clone_id integer
	JumpCloneId int32 `json:"jump_clone_id"`
	// location_id integer
	LocationId int64 `json:"location_id"`
	// location_type string
	LocationType string `json:"location_type"`
	// name string
	Name string `json:"name,omitempty"`
}
