/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// 200 ok object
type GetCorporationsCorporationIdFwStatsOk struct {
	// The enlistment date of the given corporation into faction warfare. Will not be included if corporation is not enlisted in faction warfare
	EnlistedOn time.Time `json:"enlisted_on,omitempty"`
	// The faction the given corporation is enlisted to fight for. Will not be included if corporation is not enlisted in faction warfare
	FactionId int32                                     `json:"faction_id,omitempty"`
	Kills     *GetCorporationsCorporationIdFwStatsKills `json:"kills"`
	// How many pilots the enlisted corporation has. Will not be included if corporation is not enlisted in faction warfare
	Pilots        int32                                             `json:"pilots,omitempty"`
	VictoryPoints *GetCorporationsCorporationIdFwStatsVictoryPoints `json:"victory_points"`
}
