/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// active_total object
type GetFwLeaderboardsCharactersActiveTotalActiveTotal1 struct {
	// Amount of victory points
	Amount int32 `json:"amount,omitempty"`
	// character_id integer
	CharacterId int32 `json:"character_id,omitempty"`
}
