/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 200 ok object
type GetCharactersCharacterIdMailLists200Ok struct {
	// Mailing list ID
	MailingListId int32 `json:"mailing_list_id"`
	// name string
	Name string `json:"name"`
}
