/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 200 ok object
type GetFwLeaderboardsCharactersOk struct {
	Kills         *GetFwLeaderboardsCharactersKills         `json:"kills"`
	VictoryPoints *GetFwLeaderboardsCharactersVictoryPoints `json:"victory_points"`
}
