/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 200 ok object
type GetUniversePlanetsPlanetIdOk struct {
	// name string
	Name string `json:"name"`
	// planet_id integer
	PlanetId int32                               `json:"planet_id"`
	Position *GetUniversePlanetsPlanetIdPosition `json:"position"`
	// The solar system this planet is in
	SystemId int32 `json:"system_id"`
	// type_id integer
	TypeId int32 `json:"type_id"`
}
