/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// last_week object
type GetFwLeaderboardsLastWeekLastWeek1 struct {
	// Amount of victory points
	Amount int32 `json:"amount,omitempty"`
	// faction_id integer
	FactionId int32 `json:"faction_id,omitempty"`
}
