/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// squad object
type GetFleetsFleetIdWingsSquad struct {
	// id integer
	Id int64 `json:"id"`
	// name string
	Name string `json:"name"`
}
