/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// last_week object
type GetFwLeaderboardsCorporationsLastWeekLastWeek struct {
	// Amount of kills
	Amount int32 `json:"amount,omitempty"`
	// corporation_id integer
	CorporationId int32 `json:"corporation_id,omitempty"`
}
