/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// graphic object
type GetCharactersCharacterIdMedalsGraphic struct {
	// color integer
	Color int32 `json:"color,omitempty"`
	// graphic string
	Graphic string `json:"graphic"`
	// layer integer
	Layer int32 `json:"layer"`
	// part integer
	Part int32 `json:"part"`
}
