/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// level object
type GetInsurancePricesLevel struct {
	// cost number
	Cost float32 `json:"cost"`
	// Localized insurance level
	Name string `json:"name"`
	// payout number
	Payout float32 `json:"payout"`
}
