/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Error 520
type PostCharactersCharacterIdMailError520 struct {
	// Error 520 message
	Error_ string `json:"error,omitempty"`
}
