/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// movement object
type PutFleetsFleetIdMembersMemberIdMovement struct {
	// If a character is moved to the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is moved to the `wing_commander` role, only `wing_id` should be specified. If a character is moved to the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is moved to the `squad_member` role, both `wing_id` and `squad_id` should be specified.
	Role string `json:"role"`
	// squad_id integer
	SquadId int64 `json:"squad_id,omitempty"`
	// wing_id integer
	WingId int64 `json:"wing_id,omitempty"`
}
