/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// pin object
type GetCharactersCharacterIdPlanetsPlanetIdPin struct {
	// contents array
	Contents []GetCharactersCharacterIdPlanetsPlanetIdContent `json:"contents,omitempty"`
	// expiry_time string
	ExpiryTime       time.Time                                                `json:"expiry_time,omitempty"`
	ExtractorDetails *GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails `json:"extractor_details,omitempty"`
	FactoryDetails   *GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails   `json:"factory_details,omitempty"`
	// install_time string
	InstallTime time.Time `json:"install_time,omitempty"`
	// last_cycle_start string
	LastCycleStart time.Time `json:"last_cycle_start,omitempty"`
	// latitude number
	Latitude float32 `json:"latitude"`
	// longitude number
	Longitude float32 `json:"longitude"`
	// pin_id integer
	PinId int64 `json:"pin_id"`
	// schematic_id integer
	SchematicId int32 `json:"schematic_id,omitempty"`
	// type_id integer
	TypeId int32 `json:"type_id"`
}
