/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// dogma_effect object
type GetUniverseTypesTypeIdDogmaEffect struct {
	// effect_id integer
	EffectId int32 `json:"effect_id"`
	// is_default boolean
	IsDefault bool `json:"is_default"`
}
