/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.8.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 200 ok object
type GetCorporationsCorporationIdDivisionsOk struct {
	// hangar array
	Hangar []GetCorporationsCorporationIdDivisionsHangarHangar `json:"hangar,omitempty"`
	// wallet array
	Wallet []GetCorporationsCorporationIdDivisionsWalletWallet `json:"wallet,omitempty"`
}
